### ISSUE TITLE
can register business while logged in as client

### ISSUE THREAD

**Issue by IElgohary** [SEGUC17/git-rekt-se#228]
**1. Severity:** medium
**2. Reported by:** Islam Elgohary
**3. Description:**
A logged inClient can access the business registration form, submit it and get no response.
**4. Steps to reproduce the issue:**

1) Login as a Client
2) click "Apply" in the navbar
3) fill the form and click "submit"
4) business is created but no response appears to the user

**5. Expected result:**
Logged in client should not be able to access the application form of the business or they should see a success message on registration

**Comment by melzareix** [comment]
This is not a bug, it's the intended behaviour.
