### ISSUE TITLE
Emails are not descriptive

### ISSUE THREAD

**Issue by IElgohary** [SEGUC17/git-rekt-se#232]
**1. Severity:** medium
**2. Reported by:** Islam Elgohary
**3. Description:**
emails sent to user when booking is accepted or rejected do not specify the activity or the business. 
**4. Steps to reproduce the issue:**

1) Login as a client
2) make a booking
3) logut and login as a business
4) accept or reject the booking
5) client receives on eof the below emails:
<img width="555" alt="screen shot 2017-05-01 at 12 17 08 pm" src="https://cloud.githubusercontent.com/assets/15884858/25577790/554dad7a-2e69-11e7-9f26-4c7e89c625bb.png">
<img width="529" alt="screen shot 2017-05-01 at 12 17 17 pm" src="https://cloud.githubusercontent.com/assets/15884858/25577791/556fa772-2e69-11e7-9897-ec582f1c8c12.png">

**5. Expected result:**
Email should contain the name of the activity and some information about the booking like the Date or location

**Comment by melzareix** [comment]
Not a bug in my opinion but even though I think this should be low not medium.
