### ISSUE TITLE
Logged in business gets a 404 when clicking <my page>

### ISSUE THREAD

**Issue by ameniawy** [SEGUC17/git-rekt-se#234]
**1. Severity:** 
medium
**2. Reported by:** 
Abdelrahman El Meniawy
**3. Description:**
Logged in business, clicking <My Page> from the drop down menu in the navbar gets a 404 page.
**4. Steps to reproduce the issue:**
1) Login as a business
2) Click on my account drop down menu in the navbar
3) Choose my page
4) get a 404 not found
**5. Expected result:**
Expected redirecting to my business page
![screenshot from 2017-05-01 13-37-24](https://cloud.githubusercontent.com/assets/17433149/25578989/fb843ac4-2e73-11e7-904b-e5fe3471720f.png)

**Comment by melzareix** [comment]
@ameniawy Does this happen every-time or only the first time after logging in?
