### ISSUE TITLE
Business can enter negative working hours while registering

### ISSUE THREAD

**Issue by ameniawy** [SEGUC17/git-rekt-se#235]
**1. Severity:** 
medium
**2. Reported by:** 
Abdelrahman El Meniawy
**3. Description:**
A business can enter the working hours as a negative number when registering
**4. Steps to reproduce the issue:**
1) register as a business
2) get confirmation email from the admin
3) open the link in the email
4) get the form page
5) enter a negative number in the working hours field
6) gets a success message
**5. Expected result:**
Expected a validation error message

**Comment by melzareix** [comment]
Working hours is a formatted textfield i.e you enter the details of your working hours not actual time 
```
Sat   10 AM - 12 PM
Mon 10 AM - 12 PM
Fri    Closed
```

**Comment by ameniawy** [comment]
The form is not descriptive enough then.
![screenshot from 2017-05-01 13-36-44](https://cloud.githubusercontent.com/assets/17433149/25579114/18d74660-2e75-11e7-93c7-c960f3106a3a.png)
