### ISSUE TITLE
Email used for a business can be used to register as a client

### ISSUE THREAD

**Issue by IElgohary** [SEGUC17/git-rekt-se#236]
**1. Severity:** 
Medium
**2. Reported by:** 
Islam Elgohary
**3. Description:**
An email used for a business can be used again to register as a client
**4. Steps to reproduce the issue:**
1) register as a business with an email
2) register as a client with the same email
3) user registered

**5. Expected result:**
Email should be unique

**Comment by Omarkojak** [comment]
I don't think the email should be unique if you are a business with a normal email just to make a client to book a service you should make a whole new email for that
