### ISSUE TITLE
UX, got to hit tab twice to jump to the next field

### ISSUE THREAD

**Issue by ameniawy** [SEGUC17/git-rekt-se#238]
**1. Severity:** 
low
**2. Reported by:** 
Abdelrahman El Meniawy
**3. Description:**
When submitting a form with password, to jump to the next password field i got to hit tab twice.
**4. Steps to reproduce the issue:**
1) open any form with passwords
2) click tab once, wont go to the next password field
**5. Expected result:**
click once and go to the next field

**Comment by Omarkojak** [comment]
Nope i think this issue is only with the password and confirm password fields due to the button of see password (Check it and edit the description)
