### ISSUE TITLE
footer social media links redirect to not found pages

### ISSUE THREAD

**Issue by msskzx** [SEGUC17/git-rekt-se#239]
**1. Severity:** 
medium

**2. Reported by:** 
Muhammad Khattab

**3. Description:**
facebook, twitter links in the footer redirect to not found pages

**4. Steps to reproduce the issue:**
from any page, reach the footer and click on facebook or twitter

**5. Expected result:**
redirect to the correct facebook, twitter pages

**Comment by melzareix** [comment]
The social pages are just for demonstration

**Comment by Medo3G** [comment]
These are basically placeholder links.
