### ISSUE TITLE
Business application - vague validation error message

### ISSUE THREAD

**Issue by msskzx** [SEGUC17/git-rekt-se#241]
**1. Severity:** 
medium

**2. Reported by:** 
Muhammad Khattab

**3. Description:**
Whenever the user enters a duplicate email, the response is that this business already exists not specifying which field is unique or causing the issue
 
**4. Steps to reproduce the issue:**
click apply from the nav. bar
enter duplicate email
click submit

**5. Expected result:**
more descriptive message to specify the cause of the error

**Comment by melzareix** [comment]
The only unique field is the email so it's pretty obvious that the email is the cause of the problem, we don't use usernames.

**Comment by msskzx** [comment]
I don't know whether you have unique name for the business or no so you should make that clear
