### ISSUE TITLE
2 Fields for description

### ISSUE THREAD

**Issue by ameniawy** [SEGUC17/git-rekt-se#251]
**1. Severity:** 
low
**2. Reported by:** 
Abdelrahman El meniawy
**3. Description:**
2 description fields when adding a service
**4. Steps to reproduce the issue:**
login as a business and attempt to create a service
**5. Expected result:**
1 description field
![image](https://cloud.githubusercontent.com/assets/17433149/25584580/e8965ad2-2e96-11e7-9ff9-fa145f8e3737.png)

**Comment by Medo3G** [comment]
This is not confusing. The user lacking basic comprehension of the English language is not an issue we can fix :)
