### ISSUE TITLE
Clicking on a location opens up a blank pop up with errors in the console

### ISSUE THREAD

**Issue by ameniawy** [SEGUC17/git-rekt-se#252]
**1. Severity:** 
medium
**2. Reported by:** 
Abdelrahman El meniawy
**3. Description:**
Clicking on a location opens up a blank pop up with errors in the console
**4. Steps to reproduce the issue:**
1) go to any service with an offering
2) click on the location
![image](https://cloud.githubusercontent.com/assets/17433149/25584679/4ae039d8-2e97-11e7-84c8-f2a1d45875ff.png)

**5. Expected result:**
correct location or a descriptive error message

**Comment by Medo3G** [comment]
![image](https://cloud.githubusercontent.com/assets/12884373/25584814/d8eb8052-2e97-11e7-8154-034bd4418d8b.png)

**Comment by melzareix** [comment]
You are entering a bad location that google can't find on the map, Business is expected to enter a correct location to their branches

**Comment by ameniawy** [comment]
This should be handled. If the the location entered is bad. something should replace the blank pop up.

**Comment by ameniawy** [comment]
@Medo3G the issue here is not "watch the errors in the console" like the other issue I commented on.

**Comment by ameniawy** [comment]
@Medo3G and if you take the direction of posting a screenshot, show the whole screenshot. don't  crop part of it. fair play
