### ISSUE TITLE
Can't see the top services

### ISSUE THREAD

**Issue by CRSplitter** [SEGUC17/git-rekt-se#253]
1. Severity: low

2. Reported by: Ahmed Khaled Elgabri

3. Description: Can't see the top services when visiting the homepage for the first time.

Steps to reproduce the issue: 
1- clear your history.
2-visit the homepage and check the top services section.

5. Expected result: I should see the top services.

<img width="1644" alt="issue" src="https://cloud.githubusercontent.com/assets/17381218/25585567/8ead343c-2e9b-11e7-81ed-9709f775664e.png">

after refreshing the page 

<img width="1634" alt="screen shot 2017-05-01 at 6 26 15 pm" src="https://cloud.githubusercontent.com/assets/17381218/25585606/b439549c-2e9b-11e7-9f8a-0dff9077562c.png">

**Comment by melzareix** [comment]
This is an issue with your internet connection probably, I tried the required steps and everything appears correctly, also this is not `medium` severity.

**Comment by CRSplitter** [comment]
I tried from 3 different laptops and browsers. are u sure u cleared your history?

**Comment by melzareix** [comment]
I used another browser that didn't open the site on before and everything is working, tried incognito too, I can't delete my history though tbh.

**Comment by CRSplitter** [comment]
Incognito makes no difference as you're history is still there. I cannot see the bug unless I clear my entire browser history as I've visited your website before and if this issue is with my internet then it's more convenient to each time I visit the website except that it only happens when I wipe out my entire browser history and then visit the homepage or in another scenario if I never visited your website before. Anyway, try to clear the history and visit it using chrome.

**Comment by melzareix** [comment]
Resolved.
You were visiting the non-secure version of our deployed website that makes `CORS` not working and thus the top rated services not appear you need to use `https://git-rekt.me/`
