### ISSUE TITLE
Invalid id produces wrong response

### ISSUE THREAD

**Issue by msskzx** [SEGUC17/git-rekt-se#254]
**1. Severity:** 
medium

**2. Reported by:** 
Muhammad Khattab

**3. Description:**
passing a string instead of the id to the api returns this error
response: {"errors":["Cast to ObjectId failed for value \"string\" at path \"_id\" for model \"Business\""]}
for this route /api/v1/business/:id
maybe also other routes like this: /api/v1/business/:id/edit

**4. Steps to reproduce the issue:**
type an invalid id: https://git-rekt.me/api/v1/business/id

**5. Expected result:**
validation errors should be handled or respond with 404

**Comment by melzareix** [comment]
You are trying to access the api that responds with an appropriate error message, what the problem? If you try that in the frontend you will get a 404 page.

**Comment by IElgohary** [comment]
As long as it replies with a message and doesn't change the data this is not an issue

**Comment by msskzx** [comment]
I mean you should have done like this:
https://git-rekt.me/api/v1/service/category/related/id
