### ISSUE TITLE
Limited business' branch locations

### ISSUE THREAD

**Issue by mekladious** [SEGUC17/git-rekt-se#255]
**1. Severity:**  Low

**2. Reported by:** Mira

**3. Description:** Business' branch locations are limited to 6 locations in cairo only

**4. Steps to reproduce the issue:** 
1. Signup as a business and wait for your account to be approved
2. On following the confirmation link that will be sent to your email you will be asked to enter your business' branch location

**5. Expected result:**
The business should be able to enter a location other than the provided 6(either include all location or leave it open)

![image](https://cloud.githubusercontent.com/assets/25287217/25585851/cc8a3d9e-2e9c-11e7-9114-1ae8a00b593b.png)

**Comment by melzareix** [comment]
This is the intended behaviour, the locations that we operate in are to be decided by the owner not the business the current list is for demonstration only.

**Comment by ameniawy** [comment]
Design decision
