### ISSUE TITLE
No bookings found appears for a second regardless of whether I made a booking or not

### ISSUE THREAD

**Issue by mekladious** [SEGUC17/git-rekt-se#256]
**1. Severity:** Low

**2. Reported by:** Mira

**3. Description:** If I chose to view my bookings a no bookings found error would be shown and then my bookings will appear

**4. Steps to reproduce the issue:** 
1. Sign in as a client
2. Choose profile from the nav bar then choose"My bookings"
3. An error would be shown for a second.

**5. Expected result:** This error should not be shown if I have made bookings

![nobookings](https://cloud.githubusercontent.com/assets/25287217/25586564/24847bd8-2ea0-11e7-9c74-b9418a1d7037.png)

**Comment by melzareix** [comment]
This is a placeholder while loading and is natural to appear while the loader is loading
