### ISSUE TITLE
Limited price range field in the home search

### ISSUE THREAD

**Issue by mekladious** [SEGUC17/git-rekt-se#257]
**1. Severity:** Medium

**2. Reported by:** Mira

**3. Description:** Price range is limited to 7000 in the home search, a business can have an offering of more than 7000 though

**4. Steps to reproduce the issue:** Try to search for an offering with price greater than 7000 from the home search

**5. Expected result:** Price range should be changed dynamically according to the database

**Comment by Omarkojak** [comment]
First it is till 10k+ secondly  in the backend 10k+ which means results in the query will be matching 10k plus
However since this is only frontend issue only  its severity should be only low
