### ISSUE TITLE
Client can report a review multiple times

### ISSUE THREAD

**Issue by msskzx** [SEGUC17/git-rekt-se#261]
**1. Severity:** 
medium

**2. Reported by:** 
Muhammad Khattab

**3. Description:**
client can report his own review.
client can report any review multiple times.

**4. Steps to reproduce the issue:**
review a service
click report
refresh the page then click report

**5. Expected result:**
should not allow a client to report his own review.
should not allow a client to report a review more than once.

**Comment by melzareix** [comment]
Part1 is a duplicate of #245.
Part2 is a design decision.
